<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
      <Reference Include="VintagestoryAPI">
          # NOTE you may need to change the HintPath to be a different value depending on your VintageStory install location and if you are on Windows or Linux, etc
          <HintPath>/home/chase/.local/share/vintagestory/VintagestoryAPI.dll</HintPath>
          <Private>false</Private>
      </Reference>

      <Reference Include="VintagestoryLib">
          <HintPath>/home/chase/.local/share/vintagestory/VintagestoryLib.dll</HintPath>
          <Private>false</Private>
      </Reference>
  </ItemGroup>

</Project>
